name: super_ui_kit
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_animated: ^3.2.0
  google_fonts: ^6.2.1
  responsive_framework: ^1.5.1
  intl: ^0.20.1
  lottie: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - google_fonts/
    - assets/animations/anim_dialog_success.json
    - assets/animations/anim_dialog_error.json
    - assets/animations/anim_dialog_alert.json
    - assets/animations/anim_dialog_info.json