name: super_ui_kit
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  intl: ^0.17.0
  lottie: ^2.0.0
  responsive_framework: ^0.2.0
  get: ^4.6.5
  auto_animated: ^3.1.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - google_fonts/
    - assets/animations/