name: super_notes_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  super_ui_kit:
    path: ../
  flutter: 
    sdk: flutter
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  dynamic_height_grid_view: ^0.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1


  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/animations/

