// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC76g20Eb0fHMSqz_iuSh0E3tELAYRDd3c',
    appId: '1:865350843548:web:9a8f31f12312a2da16c159',
    messagingSenderId: '865350843548',
    projectId: 'cs-super-notes',
    authDomain: 'cs-super-notes.firebaseapp.com',
    storageBucket: 'cs-super-notes.appspot.com',
    measurementId: 'G-W34Z91HJ5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_KtvqN3fafSim8F8q_teSDxlB8zNwgw',
    appId: '1:865350843548:android:96d630511243704216c159',
    messagingSenderId: '865350843548',
    projectId: 'cs-super-notes',
    storageBucket: 'cs-super-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqBarYfzFiDOlLf8XZG1cbMi1zCMIEUOg',
    appId: '1:865350843548:ios:13e442e737452a3416c159',
    messagingSenderId: '865350843548',
    projectId: 'cs-super-notes',
    storageBucket: 'cs-super-notes.appspot.com',
    iosClientId: '865350843548-g1uda3g25nhd89s6ha9f7o4adiqu0dda.apps.googleusercontent.com',
    iosBundleId: 'com.cyclicsoft.superNotesAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqBarYfzFiDOlLf8XZG1cbMi1zCMIEUOg',
    appId: '1:865350843548:ios:13e442e737452a3416c159',
    messagingSenderId: '865350843548',
    projectId: 'cs-super-notes',
    storageBucket: 'cs-super-notes.appspot.com',
    iosClientId: '865350843548-g1uda3g25nhd89s6ha9f7o4adiqu0dda.apps.googleusercontent.com',
    iosBundleId: 'com.cyclicsoft.superNotesAdmin',
  );
}
